-- CRIAR BANCO DE DADOS
CREATE DATABASE ESCOLA;

-- USAR TABLEA
USE ESCOLA;

-- CRIAR TABLE
CREATE TABLE ALUNO(
ID_ALUNO INT,
NOME_ALUNO VARCHAR(100),
ENDERECO VARCHAR(100),
CPF VARCHAR(14),
DATA_NASCIMENTO DATE
);

CREATE TABLE CURSO(
ID_CURSO INT PRIMARY KEY,

);

CREATE TABLE PROFESSOR(
ID_PROFESSOR INT PRIMARY KEY
);