-- CRIANDO O BANCO DE DADOS(DB)
CREATE DATABASE PIZZASOULS;

-- ATIVANDO O DB
USE PIZZASOULS;

-- CRIANDO A TABELA PRODUTO
CREATE TABLE PRODUTO(
 ID_PRODUTO INT PRIMARY KEY,
 NOME_PRODUTO VARCHAR(100),
 TIPO_PRODUTO VARCHAR(100),
 TAMANHO VARCHAR(1)
);

-- CRIANDO A TABELA CLIENTE
CREATE TABLE CLIENTE(
ID_CLIENTE INT PRIMARY KEY,
NOME_CLIENTE VARCHAR(100),
ENDERECO VARCHAR(100),
NUMERO INT,
CPF VARCHAR(14)
);

-- CRIANDO A TABELA FUNCIONÁRIO
CREATE TABLE FUNCIONARIO(
ID_FUNCIONARIO INT PRIMARY KEY,
NOME_FUNCIONARIO VARCHAR(100),
RE VARCHAR(4),
SALARIO INT(8),
CARGA VARCHAR(100),
SETOR VARCHAR(100),
ATIVIDADE VARCHAR(100)
);

-- CRIANDO A TABELA ESTOQUE
CREATE TABLE ESTOQUE(
ID_ESTOQUE INT PRIMARY KEY,
TIPO_ESTOQUE VARCHAR(50),
UNIDADE_MEDIDA VARCHAR(3),
DATA_ENTRADA DATE,
DATA_SAIDA DATE,
QUANTIDADE INT
);

SELECT * FROM ESTOQUE