CREATE DATABASE OFICINA_MECANICA;
USE OFICINA_MECANICA;

CREATE TABLE VEICULOS (
    ID_VEICULO INT AUTO_INCREMENT PRIMARY KEY,
    MODELO VARCHAR(50) NOT NULL,
    MARCAR VARCHAR(50) NOT NULL,
    ANO DATE NOT NULL,
    COR VARCHAR(50) NOT NULL

);

CREATE TABLE CLIENTES (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME_CLIENTE VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(100),
    ENDERECO VARCHAR(255),
    FK_VEICULO INT,
    FOREIGN KEY(FK_VEICULO) REFERENCES VEICULOS(ID_VEICULO)
);

CREATE TABLE MECANICOS (
    ID_MECANICO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_MECANICO VARCHAR(100) NOT NULL,
    SALARIO DECIMAL(6,2)
);

CREATE TABLE SERVICOS (
    ID_SERVICO INT AUTO_INCREMENT PRIMARY KEY,
    SERVICO VARCHAR(100) NOT NULL,
    DESCIRCAO VARCHAR(255) NOT NULL,
    CUSTO_SERVICO DECIMAL(8,2)
);

CREATE TABLE PRODUTO (
    ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PRODUTO VARCHAR(100) NOT NULL,
    PRECO_PRODUTO DECIMAL(8,2)
);

CREATE TABLE ESTOQUE (
    ID_ESTOQUE INT AUTO_INCREMENT PRIMARY KEY,
    QTDE INT NOT NULL,
    NOME_PRODUTO VARCHAR(100) NOT NULL,
    DATA_MOVIMENTO DATE,
    TIPO_MOVIMENTACAO VARCHAR(7),
    FK_PRODUTO INT,
    FOREIGN KEY (FK_PRODUTO) REFERENCES PRODUTO (ID_PRODUTO)
);

CREATE TABLE REALIZA (
    FK_SERVICO INT,
    FK_MECANICO INT,
    FOREIGN KEY (FK_SERVICO) REFERENCES SERVICOS(ID_SERVICO),
    FOREIGN KEY (FK_MECANICO) REFERENCES MECANICOS(ID_MECANICO)
);

