CREATE DATABASE EXEMPLO3;

USE EXEMPLO3;

CREATE TABLE CLIENTES(
COD_CLIENTE INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
NOME_CLIENTE VARCHAR(100) NOT NULL,
CPF_CLIENTE VARCHAR(14) NOT NULL,
ENDERECO VARCHAR(100) NOT NULL,
ESTADO CHAR(2) DEFAULT 'SP',
CELULAR VARCHAR(18) NOT NULL 
);

CREATE TABLE PRODUTO(
COD_PRODUTO INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
NOME_PRODUTO VARCHAR(100) NOT NULL,
VALOR DECIMAL(5,2) NOT NULL,
QNTDE INT,
DESCRICAO VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS FORNECEDOR(
COD_FORNECEDOR INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
NOME_FORNECEDOR VARCHAR(100) NOT NULL,
CNPJ VARCHAR(18) NOT NULL,
CELULAR VARCHAR(18) NOT NULL,
ENDERECO VARCHAR(100) NOT NULL
);

CREATE TABLE TEM(
COD_TEM INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
COD_FORNECEDOR INT,
COD_PRODUTO INT,
FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO (COD_PRODUTO),
FOREIGN KEY (COD_FORNECEDOR) REFERENCES FORNECEDOR (COD_FORNECEDOR)
);

SELECT * FROM PESSOA_FISICA;

ALTER TABLE PESSOA_FISICA
ADD COLUMN SEXO VARCHAR(1);

ALTER TABLE PESSOA_FISICA
RENAME TO PESSOA_FISICA;


 ALTER TABLE PESSOA_FISICA
 ADD COLUMN CIDADE VARCHAR(255);
 
 ALTER TABLE PRODUTO
 MODIFY COLUMN VALOR DECIMAL(7,2) NOT NULL;
 
 ALTER TABLE FORNECEDOR
 ADD COLUMN CIDADE VARCHAR(255),
 ADD COLUMN ESTADO VARCHAR(2) DEFAULT 'SP';
 
 DROP DATABASE EXEMPLO3;