CREATE DATABASE EXERCICIO2;

USE EXERCICIO2;

CREATE TABLE PRODUTO(
	ID_PRODUTO INT PRIMARY KEY,
    NOME_PRODUTO VARCHAR(100),
    QTDE_PRODUTO INT,
    VALOR INT,
    VALIDADE DATE
);

CREATE TABLE CLIENTES(
	ID_CLIENTE INT PRIMARY KEY,
    EMAIL VARCHAR(255),
    NOME_CLIENTE FLOAT,
    CPF INT(14),
    NUM_PEDIDO INT
);

CREATE TABLE PEDIDOS(
	ID_PEDIDO INT PRIMARY KEY,
    PRODUTO VARCHAR(100),
    CLIENTE VARCHAR(100),
    QTDE INT,
    VALOR_PEDIDO FLOAT
);

CREATE TABLE ESTOQUE(
	ID_ESTOQUE INT PRIMARY KEY,
    QTDE_ESTOQUE INT,
    DATA_ENTRADE DATETIME,
    DATA_SAIDA DATETIME
);

CREATE TABLE ORDEM_MANUTENCAO (
	ID_SERVICO INT PRIMARY KEY,
    DESCRICAO VARCHAR(255),
    DATA_MANUTECAO DATE,
    VALOR_MANUTECAO FLOAT,
    TIPO_MANUTENCAO VARCHAR(50)
);