CREATE DATABASE EXERCICIO02;

USE EXERCICIO2;

CREATE TABLE CLIENTE(
	ID_CLIENTE INT PRIMARY KEY,
    NOME_CLIENTES VARCHAR(100),
    CPF  VARCHAR(14),
    CELULAR VARCHAR(18),
    ENDERECO VARCHAR(255)
);

CREATE TABLE VEICULO(
	ID_VEICULO INT PRIMARY KEY,
    MARCA VARCHAR(20),
    STATUS_VEICULO VARCHAR(50),
    TIPO_VEICULO VARCHAR(100),
    MAXIMO_CARGO INT
);

CREATE TABLE ENTREGADOR(
	ID_ENTREGADOR INT PRIMARY KEY,
    NOME_ENTREGADOR VARCHAR(100),
    CPF VARCHAR(14),
    CERTIFICADOS VARCHAR(100),
    EMAIL VARCHAR(255)
);

CREATE TABLE ENTREGA(
	ID_ENTREGA INT PRIMARY KEY,
    DESCRICAO_ENTREGA VARCHAR(100),
    TIPO_ENTREGA VARCHAR(50),
    DATA_LIMITE DATE,
    STATUS_ENTREGA VARCHAR(50)
);

CREATE TABLE GARRAGEM(
	ID_GARRAGEM INT PRIMARY KEY,
    LOCAL VARCHAR(50),
    QTDE_VAGAS INT,
    QTDE_VEICULOS INT,
    VALOR FLOAT
);