-- CRIAR BANCO DE DADOS --
CREATE DATABASE EXEMPLO2;

-- ATIVAR BANCO DE DADOS --
USE EXEMPLO2;

CREATE TABLE CLIENTE (
	COD_CLIENTE INT PRIMARY KEY,
    NOME_CLIENTE VARCHAR(100),
    ENDERECO VARCHAR(255),
    CPF VARCHAR(14),
    CELULAR VARCHAR(18)
);

CREATE TABLE ESTOQUE (
	COD_ESTOQUE INT PRIMARY KEY,
    PRODUTO VARCHAR(100),
    QTDE INT,
    VALIDADE DATE
);

CREATE TABLE PRODUTOS (
	COD_PRODUTO INT PRIMARY KEY,
    NOME_PRODUTO VARCHAR(100),
    QTDE INT,
    VALOR FLOAT,
    VALIDADE DATE
);

CREATE TABLE FUNCIONARIO(
	COD_FUNCIONARIO INT PRIMARY KEY,
    NOME_FUNCIONARIO VARCHAR(100),
    CPF_FUNCIONARIO VARCHAR(14),
    DATA_NASCIMENTO DATE,
    SALARIO FLOAT
 );
 
 -- CONSULTA DE TABELAS --
SELECT * FROM CLIENTE, ESTOQUE;

SELECT NOME_CLIENTE, NOME_FUNCIONARIO, NOME_PRODUTO FROM CLIENTE, ESTOQUE, FUNCIONARIO, PRODUTOS;