CREATE DATABASE IF NOT EXISTS BIBLIOTECA;
USE BIBLIOTECA;

CREATE TABLE LIVRO (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(80) NOT NULL,
    GENERO VARCHAR(30) NOT NULL,
    AUTOR VARCHAR(80) NOT NULL,
    lSTATUS VARCHAR(15) NOT NULL DEFAULT 'DISPONÍVEL',
    EDITORA VARCHAR(50),
    ANO_LANCAMENTO DATE
);

CREATE TABLE CLIENTE (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(80) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    EMAIL VARCHAR(80) NOT NULL,
    TELEFONE VARCHAR(19) NOT NULL
);

-- INSERINDO DADOS DO LIVRO
INSERT INTO LIVRO (TITULO, GENERO, AUTOR, lSTATUS, EDITORA, ANO_LANCAMENTO) VALUES ('Omniscient Reader\'s Viewpoint', 'Fantasia', 'Sing Shong', '', 'Redice Studio', '2021-01-15');
INSERT INTO LIVRO (TITULO, GENERO, AUTOR, lSTATUS, EDITORA, ANO_LANCAMENTO) VALUES ('Harry Potter e a Pedra Filosofal', 'Fantasia', 'J.K. Rowling', '', 'Rocco', '1997-06-26');
INSERT INTO LIVRO (TITULO, GENERO, AUTOR, lSTATUS, EDITORA, ANO_LANCAMENTO) VALUES ('O Senhor dos Anéis: A Sociedade do Anel', 'Fantasia', 'J.R.R. Tolkien', '', 'Martins Fontes', '1954-07-29');
INSERT INTO LIVRO (TITULO, GENERO, AUTOR, lSTATUS, EDITORA, ANO_LANCAMENTO) VALUES ('O Pequeno Príncipe', 'Infantil', 'Antoine de Saint-Exupéry', '', 'Agir', '1943-04-06');
INSERT INTO LIVRO (TITULO, GENERO, AUTOR, lSTATUS, EDITORA, ANO_LANCAMENTO) VALUES ('O Retrato de Dorian Gray', 'Romance', 'Oscar Wilde', '', 'Martin Claret', '1890-06-20');
INSERT INTO LIVRO (TITULO, GENERO, AUTOR, lSTATUS, EDITORA, ANO_LANCAMENTO) VALUES ('Dom Casmurro', 'Romance', 'Machado de Assis', '', 'Garnier', '1899-01-01');
INSERT INTO LIVRO (TITULO, GENERO, AUTOR, lSTATUS, EDITORA, ANO_LANCAMENTO) VALUES ('Memórias Póstumas de Brás Cubas', 'Romance', 'Machado de Assis', '', 'Garnier', '1881-01-01');
INSERT INTO LIVRO (TITULO, GENERO, AUTOR, lSTATUS, EDITORA, ANO_LANCAMENTO) VALUES ('O Hobbit', 'Fantasia', 'J.R.R. Tolkien', '', 'Martins Fontes', '1937-09-21');

-- INSERINDO DADOS DO CLIENTE
INSERT INTO CLIENTE (NOME, CPF, EMAIL, TELEFONE) VALUES ('Ana Souza', '123.456.789-00', 'ana.souza@email.com', '(11) 98765-4321');
INSERT INTO CLIENTE (NOME, CPF, EMAIL, TELEFONE) VALUES ('Bruno Lima', '987.654.321-00', 'bruno.lima@email.com', '(21) 91234-5678');
INSERT INTO CLIENTE (NOME, CPF, EMAIL, TELEFONE) VALUES ('Carla Mendes', '111.222.333-44', 'carla.mendes@email.com', '(31) 99876-5432');
INSERT INTO CLIENTE (NOME, CPF, EMAIL, TELEFONE) VALUES ('Daniel Rocha', '555.666.777-88', 'daniel.rocha@email.com', '(41) 91234-8765');

-- SELECT
SELECT * FROM LIVRO;
SELECT * FROM CLIENTE;

-- ATUALIZANDO
UPDATE LIVRO
SET lSTATUS = 'INDISPONÍVEL'
WHERE ID >= 4;

UPDATE CLIENTE
SET TELEFONE = '(19) 98765-4321'
WHERE NOME = 'Carla Mendes';

-- ESVAZIANDO A TABELA
DELETE FROM LIVRO;
DELETE FROM CLIENTE;
