CREATE DATABASE RESERVA_DE_EQUIPAMENTOS;

USE RESERVA_DE_EQUIPAMENTOS;

CREATE TABLE EQUIPAMENTO(
COD_EQUIPAMENTO INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
NOME_EQUIPAMENTO VARCHAR(100) NOT NULL,
STATUS VARCHAR(50),
CATEGORIA VARCHAR(50),
DESCRICAO VARCHAR(100)
);

CREATE TABLE USUARIO(
COD_USUARIO INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
NOME_USUARIO VARCHAR(100) NOT NULL,
CPF_USUAIRO VARCHAR(14) NOT NULL,
TIPO_USUARIO VARCHAR(50),
EMAIL VARCHAR(100)
);

CREATE TABLE LOCAL(
COD_LOCAL INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
NOME_LOCAL VARCHAR(100) NOT NULL,
TIPO_LOCAL VARCHAR(50),
CAPACIDADE INT,
DESCRICAO VARCHAR(100)
);

CREATE TABLE RESERVA(
COD_RESERVA INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
QNTDE INT NOT NULL,
DATA_DEVOLUCAO DATETIME,
DATA_RESERVA DATETIME,
DATA_RETIRADA DATETIME
);

CREATE TABLE ESTOQUE(
COD_ESTOQUE INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
UNIDADE VARCHAR(3),
DATA_ENTRADA DATETIME,
DATA_SAIDA DATETIME,
QNTDE INT
);

CREATE TABLE VAI(
COD_VAI INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
COD_EQUIPAMENTO INT,
COD_ESTOQUE INT,
FOREIGN KEY (COD_EQUIPAMENTO) REFERENCES EQUIPAMENTO (COD_EQUIPAMENTO),
FOREIGN KEY (COD_ESTOQUE) REFERENCES ESTOQUE (COD_ESTOQUE)
);

CREATE TABLE TEM(
COD_TEM INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
COD_USUARIO INT,
COD_LOCAL INT,
COD_RESERVA INT,
FOREIGN KEY (COD_USUARIO) REFERENCES USUARIO (COD_USUARIO),
FOREIGN KEY (COD_LOCAL) REFERENCES LOCAL (COD_LOCAL),
FOREIGN KEY (COD_RESERVA) REFERENCES RESERVA (COD_RESERVA)
);