CREATE DATABASE DDL;

USE DLL;

CREATE TABLE PECA(
	Pcodigo INT AUTO_INCREMENT PRIMARY KEY,
    Pnome VARCHAR(100) NOT NULL,
    peso DECIMAL(10,2) NOT NULL,
    cor VARCHAR(50) NOT NULL,
    cidade VARCHAR(80) NOT NULL
);

CREATE TABLE FORNECEDOR(
	Fcodigo INT AUTO_INCREMENT PRIMARY KEY,
    Fnome VARCHAR(100) NOT NULL,
    cidade VARCHAR(80),
    status VARCHAR(25) NOT NULL DEFAULT 'ATIVO'
);

CREATE TABLE INSTITUICAO(
	Icodigo INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL
);

CREATE TABLE PROJETO(
 PRcodigo INT AUTO_INCREMENT PRIMARY KEY,
 FOREIGN KEY (Icod) REFERENCES INSTITUICAO (Icodigo),
 PRnome VARCHAR(100) NOT NULL,
 cidade VARCHAR(80) 
);

CREATE TABLE Fornecimento (
Pcodigo INT AUTO_INCREMENT NOT NULL,
Fcodigo INT AUTO_INCREMENT NOT NULL,
PRcodigo INT AUTO_INCREMENT NOT NULL,
FOREIGN KEY(Pcodigo) REFERENCES Peca (Pcodigo),
FOREIGN KEY(Fcodigo) REFERENCES Fornecedor (Fcodigo),
FOREIGN KEY(PRcodigo) REFERENCES Projeto (PRcodigo)
)
