CREATE DATABASE DB_JOINS;
USE DB_JOINS;

CREATE TABLE CLIENTE (
	CODCLI CHAR(3) NOT NULL PRIMARY KEY,
    NOME VARCHAR(40) NOT NULL,
    ENDERECO VARCHAR(50) NOT NULL,
    CIDADE VARCHAR(20) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    CEP CHAR(9) NOT NULL
);

CREATE TABLE VENDA (
	DUPLIC CHAR(6) NOT NULL PRIMARY KEY,
    VALOR DECIMAL(10,2) NOT NULL,
    VENCTO DATE NOT NULL,
    CODCLI CHAR(3),
    FOREIGN KEY (CODCLI) REFERENCES CLIENTE (CODCLI)
);

SELECT * FROM CLIENTE;
SELECT * FROM VENDA;


INSERT INTO CLIENTE VALUES('250', 'BANCO BARCA S/A', 'R. VIO, 34', 'SAO SEBASTIAO', 'CE', '62380-000');
INSERT INTO CLIENTE VALUES('820', 'MECANICA SAO PAULA', 'R. DO MACUCO, 99', 'SANTA ANTONIO', 'ES', '29810-020');
INSERT INTO CLIENTE VALUES('170', 'POSTO BRASIL LTDA. ', 'AV. IMPERIO, 85', 'GUAGIRUS', 'BA', '42837-000');
INSERT INTO VENDA VALUES('230001', '1300.00', '2001-06-10', '250');
INSERT INTO VENDA VALUES('230099', '1000.00', '2002-10-02', '170');
INSERT INTO VENDA VALUES('997818', '3000.00', '2001-11-11', '820');


INSERT INTO CLIENTE VALUES('42', 'BANCO BARCA S/A', 'R. MAGRIN, 12', 'PERA', 'CX', '62484-000');
INSERT INTO CLIENTE VALUES('205', 'IFOOD', 'R. VIO, 64', 'SANTA SEBASTIAO', 'XE', '62381-000');

SELECT VENDA.DUPLIC, CLIENTE.NOME
FROM CLIENTE, VENDA
WHERE CLIENTE.CODCLI = VENDA.CODCLI;

SELECT VENDA.DUPLIC, CLIENTE.NOME
FROM CLIENTE INNER JOIN VENDA ON CLIENTE.CODCLI = VENDA.CODCLI;

SELECT VEN.DUPLIC, CLI.NOME
FROM CLIENTE CLI INNER JOIN VENDA VEN ON CLI.CODCLI = VEN.CODCLI;

SELECT VEN.DUPLIC, CLI.NOME, CLI.CIDADE
FROM CLIENTE CLI RIGHT JOIN VENDA VEN ON CLI.CODCLI = VEN.CODCLI
ORDER BY CLI.NOME;

SELECT CLI.NOME, CLI.NOME
FROM CLIENTE CLI LEFT JOIN VENDA VEN ON CLI.CODCLI = VEN.CODCLI
ORDER BY CLI.NOME;

SELECT CLI.NOME, CLI.NOME
FROM CLIENTE CLI RIGHT JOIN VENDA VEN ON CLI.CODCLI = VEN.CODCLI
ORDER BY CLI.NOME;

SELECT CLIENTE.NOME, COUNT(*) AS QTDE
FROM CLIENTE INNER JOIN VENDA ON CLIENTE.CODCLI - VENDA.CODCLI
GROUP BY CLIENTE.NOME;

SELECT CLIENTE.NOME, SUM(VALOR) AS TOTAL
FROM CLIENTE INNER JOIN VENDA ON CLIENTE.CODCLI = VENDA.CODCLI
GROUP BY CLIENTE.NOME;