	CREATE DATABASE REMOTERC;
	USE REMOTERC;
	SELECT DATABASE();

	CREATE TABLE PRODUTO(
		ID INT AUTO_INCREMENT PRIMARY KEY,
		UNIDADE CHAR(3) NOT NULL,
		DESCRICAO VARCHAR(30) NOT NULL,
		VALOR_UNIT DECIMAL(7,2) NOT NULL
	);

	SELECT * FROM PRODUTO;

	INSERT INTO PRODUTO(UNIDADE, DESCRICAO, VALOR_UNIT) VALUES ('g', 'Elefante de mesa', '12');
	INSERT INTO PRODUTO(UNIDADE, DESCRICAO, VALOR_UNIT) VALUES ('m/s', 'teclado gaymer', '94949');
	INSERT INTO PRODUTO(UNIDADE, DESCRICAO, VALOR_UNIT) VALUES ('t', 'pão', '32876');

	-- ATUALIZAÇÃO DE VALORES
	UPDATE PRODUTO
	SET VALOR_UNIT = 32.00
	WHERE DESCRICAO = 'teclado gaymer';

	UPDATE PRODUTO
	SET VALOR_UNIT = 28.00, DESCRICAO = "PÃO DE FORMA"
	WHERE ID = 2;

	UPDATE PRODUTO
	SET VALOR_UNIT = VALOR_UNIT + (VALOR_UNIT * 0.1);
    
    
CREATE TABLE VENDEDOR(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(20) NOT NULL,
    SALARIO DECIMAL(7,2) NOT NULL,
    FSALARIAL CHAR(1) NOT NULL
);

SELECT * FROM VENDEDOR;

INSERT INTO VENDEDOR(NOME, SALARIO, FSALARIAL) VALUES ('BENZA', 1922.78, '3');
INSERT INTO VENDEDOR(NOME, SALARIO, FSALARIAL) VALUES ('SENKOU', 94534.78, '1');
INSERT INTO VENDEDOR(NOME, SALARIO, FSALARIAL) VALUES ('BENZA', 702.78, '2');

UPDATE VENDEDOR
SET SALARIO = '3150.00'
WHERE FSALARIAL = 1;

UPDATE VENDEDOR
SET SALARIO = SALARIO + (SALARIO * 0.1)
WHERE FSALARIAL = 2;

UPDATE VENDEDOR
SET SALARIO = '3500.00'
WHERE FSALARIAL = 3;

DELETE FROM VENDEDOR
WHERE SALARIO < 2500.00;

DELETE FROM PRODUTO;

-- Registro único
DELETE FROM PRODUTOS WHERE ID = '1';

-- Intervalo (operador AND)
DELETE FROM VENDEDOR WHERE FSALARIAL >= 1 AND ID <=2;

-- ESVAZIANDO A TABELA
DELETE FROM CLIENTES

TRUNCATE TABLE PRODDUTO;