CREATE DATABASE DDL;

USE DDL;

CREATE TABLE PECA(
	Pcodigo INT AUTO_INCREMENT PRIMARY KEY,
    Pnome VARCHAR(100) NOT NULL,
    peso DECIMAL(10,2) NOT NULL,
    cor VARCHAR(50) NOT NULL,
    cidade VARCHAR(80) NOT NULL
);

CREATE TABLE FORNECEDOR(
	Fcodigo INT AUTO_INCREMENT PRIMARY KEY,
    Fnome VARCHAR(100) NOT NULL,
    cidade VARCHAR(80),
    status VARCHAR(25) NOT NULL DEFAULT 'ATIVO'
);

CREATE TABLE INSTITUICAO(
	Icodigo INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL
);

CREATE TABLE PROJETO(
 PRcodigo INT AUTO_INCREMENT PRIMARY KEY,
 Icod INT NOT NULL,
 FOREIGN KEY (Icod) REFERENCES INSTITUICAO (Icodigo),
 PRnome VARCHAR(100) NOT NULL,
 cidade VARCHAR(80) 
);

CREATE TABLE Fornecimento (
Pcodigo INT,
Fcodigo INT,
PRcodigo INT,
FOREIGN KEY(Pcodigo) REFERENCES Peca (Pcodigo),
FOREIGN KEY(Fcodigo) REFERENCES Fornecedor (Fcodigo),
FOREIGN KEY(PRcodigo) REFERENCES Projeto (PRcodigo)
);

CREATE TABLE CIDADE (
Ccod INT AUTO_INCREMENT PRIMARY KEY,
Cnome VARCHAR(100) NOT NULL,
UF VARCHAR(2) DEFAULT 'SP'
);

ALTER TABLE FORNECEDOR
ADD COLUMN Fone varchar(100),
ADD COLUMN Ccod INT;

ALTER TABLE FORNECEDOR
ADD CONSTRAINT fkFCod
FOREIGN KEY (Ccod) REFERENCES CIDADE (Ccod);

ALTER TABLE PECA
ADD COLUMN Ccod INT;

ALTER TABLE PECA
ADD CONSTRAINT fkPCod
FOREIGN KEY (Ccod) REFERENCES CIDADE (Ccod);

ALTER TABLE PROJETO
ADD COLUMN FkPRCcod INT;

ALTER TABLE PROJETO
ADD CONSTRAINT fkPRCod
FOREIGN KEY (Ccod) REFERENCES CIDADE (Ccod);



